{
  "files": 1, 
  "nb_test": 1063, 
  "nb_error": 1, 
  "classification": {
    "singleLine": false
  }, 
  "failing_tests": [
    "typeutils.runtime.kryo.KryoClearedBufferTest"
  ], 
  "patch": "diff --git a/flink-java/src/main/java/org/apache/flink/api/java/typeutils/runtime/kryo/KryoSerializer.java b/flink-java/src/main/java/org/apache/flink/api/java/typeutils/runtime/kryo/KryoSerializer.java\nindex f825fc6353..8549e26441 100644\n--- a/flink-java/src/main/java/org/apache/flink/api/java/typeutils/runtime/kryo/KryoSerializer.java\n+++ b/flink-java/src/main/java/org/apache/flink/api/java/typeutils/runtime/kryo/KryoSerializer.java\n@@ -182,11 +182,22 @@ public void serialize(T record, DataOutputView target) throws IOException {\n \t\t\tpreviousOut = target;\n \t\t}\n \n+\t\t// Sanity check: Make sure that the output is cleared/has been flushed by the last call\n+\t\t// otherwise data might be written multiple times in case of a previous EOFException\n+\t\tif (output.position() != 0) {\n+\t\t\tthrow new IllegalStateException(\"The Kryo Output still contains data from a previous \" +\n+\t\t\t\t\"serialize call. It has to be flushed or cleared at the end of the serialize call.\");\n+\t\t}\n+\n \t\ttry {\n \t\t\tkryo.writeClassAndObject(output, record);\n \t\t\toutput.flush();\n \t\t}\n \t\tcatch (KryoException ke) {\n+\t\t\t// make sure that the Kryo output buffer is cleared in case that we can recover from\n+\t\t\t// the exception (e.g. EOFException which denotes buffer full)\n+\t\t\toutput.clear();\n+\n \t\t\tThrowable cause = ke.getCause();\n \t\t\tif (cause instanceof EOFException) {\n \t\t\t\tthrow (EOFException) cause;\n", 
  "project": "flink", 
  "linesAdd": 11, 
  "jira_id": "2800", 
  "nb_skipped": 0, 
  "commit": "b654e989", 
  "nb_failure": 0, 
  "linesRem": 0
}